# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
